-- Seed data: a curated sample of recognizable NFL players for the draft board.
-- This is an offline fallback, not the live source. Run `npm run import:players`
-- (scripts/import-players.mjs) to replace the offensive/K/DST pool with current
-- FantasyPros half-PPR rankings; that import keeps the IDP rows below untouched.
-- is_idp = true marks individual defensive players (filtered out when a draft excludes IDPs).

insert into public.players (name, position, team, is_idp) values
  -- Quarterbacks
  ('Patrick Mahomes', 'QB', 'KC', false),
  ('Josh Allen', 'QB', 'BUF', false),
  ('Jalen Hurts', 'QB', 'PHI', false),
  ('Lamar Jackson', 'QB', 'BAL', false),
  ('Joe Burrow', 'QB', 'CIN', false),
  ('Justin Herbert', 'QB', 'LAC', false),
  ('C.J. Stroud', 'QB', 'HOU', false),
  ('Jayden Daniels', 'QB', 'WAS', false),
  ('Dak Prescott', 'QB', 'DAL', false),
  ('Jared Goff', 'QB', 'DET', false),
  ('Kyler Murray', 'QB', 'ARI', false),
  ('Tua Tagovailoa', 'QB', 'MIA', false),
  ('Brock Purdy', 'QB', 'SF', false),
  ('Anthony Richardson', 'QB', 'IND', false),
  ('Caleb Williams', 'QB', 'CHI', false),
  ('Trevor Lawrence', 'QB', 'JAX', false),
  ('Jordan Love', 'QB', 'GB', false),
  ('Kirk Cousins', 'QB', 'ATL', false),
  ('Aaron Rodgers', 'QB', 'NYJ', false),
  ('Matthew Stafford', 'QB', 'LAR', false),
  -- Running backs
  ('Christian McCaffrey', 'RB', 'SF', false),
  ('Bijan Robinson', 'RB', 'ATL', false),
  ('Breece Hall', 'RB', 'NYJ', false),
  ('Jahmyr Gibbs', 'RB', 'DET', false),
  ('Saquon Barkley', 'RB', 'PHI', false),
  ('Jonathan Taylor', 'RB', 'IND', false),
  ('Derrick Henry', 'RB', 'BAL', false),
  ('De''Von Achane', 'RB', 'MIA', false),
  ('Kyren Williams', 'RB', 'LAR', false),
  ('Josh Jacobs', 'RB', 'GB', false),
  ('Travis Etienne', 'RB', 'JAX', false),
  ('Isiah Pacheco', 'RB', 'KC', false),
  ('Joe Mixon', 'RB', 'HOU', false),
  ('Kenneth Walker III', 'RB', 'SEA', false),
  ('James Cook', 'RB', 'BUF', false),
  ('Rachaad White', 'RB', 'TB', false),
  ('Aaron Jones', 'RB', 'MIN', false),
  ('Alvin Kamara', 'RB', 'NO', false),
  ('David Montgomery', 'RB', 'DET', false),
  ('Najee Harris', 'RB', 'PIT', false),
  ('D''Andre Swift', 'RB', 'CHI', false),
  ('Brian Robinson Jr.', 'RB', 'WAS', false),
  ('Tony Pollard', 'RB', 'TEN', false),
  ('Zamir White', 'RB', 'LV', false),
  ('Rhamondre Stevenson', 'RB', 'NE', false),
  -- Wide receivers
  ('Tyreek Hill', 'WR', 'MIA', false),
  ('CeeDee Lamb', 'WR', 'DAL', false),
  ('Ja''Marr Chase', 'WR', 'CIN', false),
  ('Justin Jefferson', 'WR', 'MIN', false),
  ('Amon-Ra St. Brown', 'WR', 'DET', false),
  ('A.J. Brown', 'WR', 'PHI', false),
  ('Puka Nacua', 'WR', 'LAR', false),
  ('Garrett Wilson', 'WR', 'NYJ', false),
  ('Chris Olave', 'WR', 'NO', false),
  ('Drake London', 'WR', 'ATL', false),
  ('Nico Collins', 'WR', 'HOU', false),
  ('Marvin Harrison Jr.', 'WR', 'ARI', false),
  ('Davante Adams', 'WR', 'LV', false),
  ('Mike Evans', 'WR', 'TB', false),
  ('DK Metcalf', 'WR', 'SEA', false),
  ('DeVonta Smith', 'WR', 'PHI', false),
  ('Stefon Diggs', 'WR', 'HOU', false),
  ('Brandon Aiyuk', 'WR', 'SF', false),
  ('Deebo Samuel', 'WR', 'SF', false),
  ('Cooper Kupp', 'WR', 'LAR', false),
  ('DJ Moore', 'WR', 'CHI', false),
  ('Tee Higgins', 'WR', 'CIN', false),
  ('Jaylen Waddle', 'WR', 'MIA', false),
  ('Keenan Allen', 'WR', 'CHI', false),
  ('Michael Pittman Jr.', 'WR', 'IND', false),
  ('George Pickens', 'WR', 'PIT', false),
  ('Zay Flowers', 'WR', 'BAL', false),
  ('Christian Kirk', 'WR', 'JAX', false),
  ('Calvin Ridley', 'WR', 'TEN', false),
  ('Terry McLaurin', 'WR', 'WAS', false),
  ('Amari Cooper', 'WR', 'CLE', false),
  ('Diontae Johnson', 'WR', 'CAR', false),
  ('Rome Odunze', 'WR', 'CHI', false),
  ('Malik Nabers', 'WR', 'NYG', false),
  ('Jordan Addison', 'WR', 'MIN', false),
  ('Jayden Reed', 'WR', 'GB', false),
  -- Tight ends
  ('Travis Kelce', 'TE', 'KC', false),
  ('Sam LaPorta', 'TE', 'DET', false),
  ('Mark Andrews', 'TE', 'BAL', false),
  ('Trey McBride', 'TE', 'ARI', false),
  ('George Kittle', 'TE', 'SF', false),
  ('Dalton Kincaid', 'TE', 'BUF', false),
  ('Evan Engram', 'TE', 'JAX', false),
  ('Kyle Pitts', 'TE', 'ATL', false),
  ('David Njoku', 'TE', 'CLE', false),
  ('T.J. Hockenson', 'TE', 'MIN', false),
  ('Dallas Goedert', 'TE', 'PHI', false),
  ('Jake Ferguson', 'TE', 'DAL', false),
  -- Kickers
  ('Justin Tucker', 'K', 'BAL', false),
  ('Harrison Butker', 'K', 'KC', false),
  ('Brandon Aubrey', 'K', 'DAL', false),
  ('Jake Elliott', 'K', 'PHI', false),
  ('Tyler Bass', 'K', 'BUF', false),
  ('Jake Moody', 'K', 'SF', false),
  -- Team defenses
  ('San Francisco 49ers', 'DST', 'SF', false),
  ('Dallas Cowboys', 'DST', 'DAL', false),
  ('Baltimore Ravens', 'DST', 'BAL', false),
  ('Buffalo Bills', 'DST', 'BUF', false),
  ('New York Jets', 'DST', 'NYJ', false),
  ('Cleveland Browns', 'DST', 'CLE', false),
  ('Pittsburgh Steelers', 'DST', 'PIT', false),
  ('Kansas City Chiefs', 'DST', 'KC', false),
  -- Individual defensive players (IDP)
  ('Micah Parsons', 'LB', 'DAL', true),
  ('T.J. Watt', 'LB', 'PIT', true),
  ('Myles Garrett', 'DL', 'CLE', true),
  ('Nick Bosa', 'DL', 'SF', true),
  ('Maxx Crosby', 'DL', 'LV', true),
  ('Aidan Hutchinson', 'DL', 'DET', true),
  ('Fred Warner', 'LB', 'SF', true),
  ('Roquan Smith', 'LB', 'BAL', true),
  ('Bobby Wagner', 'LB', 'WAS', true),
  ('Foyesade Oluokun', 'LB', 'JAX', true),
  ('Zaire Franklin', 'LB', 'IND', true),
  ('Quay Walker', 'LB', 'GB', true),
  ('Derwin James', 'DB', 'LAC', true),
  ('Antoine Winfield Jr.', 'DB', 'TB', true),
  ('Minkah Fitzpatrick', 'DB', 'PIT', true),
  ('Kyle Hamilton', 'DB', 'BAL', true),
  ('Budda Baker', 'DB', 'ARI', true),
  ('Patrick Surtain II', 'DB', 'DEN', true),
  ('Sauce Gardner', 'DB', 'NYJ', true),
  ('Talanoa Hufanga', 'DB', 'SF', true),
  ('Will Anderson Jr.', 'DL', 'HOU', true),
  ('Chris Jones', 'DL', 'KC', true),
  ('Danielle Hunter', 'DL', 'HOU', true),
  ('Josh Allen', 'DL', 'JAX', true),
  ('Brian Burns', 'DL', 'NYG', true);
